# Documentation: https://docs.travis-ci.com/user/languages/julia/
language: julia

os:
  - linux
  # - osx

julia:
  - 1.5
  # - 1 # uncomment when 1.6 is out
  - nightly

notifications:
  email: false

jobs:
  include:
    - stage: "Documentation"
      julia: 1
      os: linux
      script:
        - julia --project=docs/ -e 'using Pkg; Pkg.develop(PackageSpec(path=pwd()));
                                               Pkg.instantiate()'
        - julia --project=docs/ docs/make.jl
      after_success: skip

  allow_failures:
    - julia: nightly

## uncomment the following lines to override the default test script
script:
 - julia --color=yes -e 'using Pkg; Pkg.activate(); Pkg.instantiate(); Pkg.test()'
